# -*- coding: utf-8 -*-
"""Challenge-Aiut.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zola8Bf-_sEMAC14zoxKHqcVY5QkDUfZ

Challenge: Análisis de tickets AIUT
¡Hola científica/científico de datos! Aquí tienes el challenge.

Planteamiento del problema: Tu que trabajas en AIUT. Te han asignado a la división de análisis de datos de tickets.

El trabajo de esta división es crucial, una de sus labores principales es recopilar los datos necesarios para implementar un sistema de analisis de tickets.

El equipo que implementará el modelo necesita que generemos el código para realizar 3 tareas de consulta. Prepara el código para que puedan realizar esas tareas:


1.   Obtener el comentario más solicitado
2.   Cuales son las horas más solicitadas para instalaciones
3.   Cuál es el tiempo que más ha durado un ticket
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

aiutdf=pd.read_csv("aiutofficer.csv")

df_2 = aiutdf["KOMENTARZ"].str.split(" - ", expand = True)
df_2.columns = ["ID", "SERVICE-NAME"]

aiutdf = pd.concat([aiutdf,df_2], axis = 1)

aiutdf=aiutdf.drop(["KOMENTARZ"], axis=1)

"""#1. Obtener el comentario (SERVICE-NAME) más solicitado"""

#1. Obtener el comentario (SERVICE-NAME) más solicitado
df_ticket = aiutdf.groupby(by = ['SERVICE-NAME']).count().reset_index() 
df_ticket = pd.DataFrame(df_ticket,columns = ['SERVICE-NAME','DATA'])
df_ticket = df_ticket.sort_values(by='DATA',ascending=False)
df_ticket

plt.barh(df_ticket['SERVICE-NAME'],df_ticket['DATA'])
plt.show()

"""#2.   Cuales son las horas más solicitadas para instalaciones

"""

df_hour = aiutdf.groupby(by = ['OD']).count().reset_index() 
df_hour

"""#3.   Cuál es el tiempo que más ha durado un ticket"""

